### ISSUE TITLE
chore: webhooks 2.0

### ISSUE THREAD

**Issue by chris13524** [WalletConnect/archive-server#1]
```[tasklist]
### Tasks
- [x] Breakout integration and unit tests
- [ ] Submit PRs for JS client
- [ ] Permenant keypair
- [ ] Unregistration endpoint
- [ ] Remove old registration endpoints and rename to remove v2
```

**Comment by chris13524** [comment]
Closing as Archive Server has been removed.
